In [3]:
x = 10
y = x
x is y

True

In [ ]:
x = ['top1', 'top2']
y = x
print(x is y)
y = ['qapi', 'oyuncu'] # avtomatik yeni qutu yaradir
print(x is y)

True
False


In [12]:
x = ['a', 'b', 'c']
y = x
print(x is y)
y[0] = 'Z'
print(y)
print(x)
print(x is y)

True
['Z', 'b', 'c']
['Z', 'b', 'c']
True


In [15]:
x = ['a', 'b', 'c']
y = x.copy()
print(x is y)
y[0] = 'Z'
print(y)
print(x)

False
['Z', 'b', 'c']
['a', 'b', 'c']


In [23]:
import copy
x = [['a','b','c'], [1,2,3]]
y = copy.deepcopy(x)
print(x is y)
x[0][0] = 'Z'
print(x)
print(y)

False
[['Z', 'b', 'c'], [1, 2, 3]]
[['a', 'b', 'c'], [1, 2, 3]]


In [24]:
x = [1, 2, 3]
y = x
y = ['a', 'b', 'c'] # This will create a new object in memory and assign it to y
print(x) # Output: [1, 2, 3]
print(y) # Output: ['a', 'b', 'c']
print(x is y) # Output: False

[1, 2, 3]
['a', 'b', 'c']
False


In [27]:
from pathlib import Path
hazirki_yerim = Path.cwd()
hazirki_yerim

WindowsPath('c:/Users/user/Desktop/div')

In [29]:
yeni_folder = hazirki_yerim / 'salammoloykum'
yeni_folder

WindowsPath('c:/Users/user/Desktop/div/salammoloykum')

In [30]:
yeni_folder.mkdir()

In [31]:
yeni_folder.exists()

True

In [32]:
yeni_fayl = yeni_folder / 'salam.txt'
yeni_fayl

WindowsPath('c:/Users/user/Desktop/div/salammoloykum/salam.txt')

In [35]:
yeni_fayl.write_text('salam')

5

In [37]:
yeni_fayl.read_text()

'salam \nalsdjfals\nalsdjfal'

In [42]:
with open(yeni_fayl, 'w') as f:
    f.write('sagol\ngecen xeyre qalsin')


In [44]:
with open(yeni_fayl, 'a') as f:
    f.write('\ngoruserik')

In [46]:
m = [100,200,300,400]
b = [10,20,30,40]

mpb = []
for i in range(4):
    mpb.append(m[i] + b[i])
    
mpb

[110, 220, 330, 440]

In [47]:
m + b

[100, 200, 300, 400, 10, 20, 30, 40]

In [49]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [56]:
import numpy as np

In [ ]:
# m = [100,200,300,400]
# b = [10,20,30,40]

m = np.array([100,200,300,400])
b = np.array([10,20,30,40])

m + b

array([110, 220, 330, 440])

In [ ]:
type(m) # n dimensional

numpy.ndarray

In [75]:
arr_1 = np.array([10,11,12])
arr_2 = np.array([
    [10,11,12], 
    [100,111,122],
])
arr_3 = np.array([
    [
        [10,11,12,100], 
        [10,11,12,100], 
    	[100,111,122,100],
    ],
    [
        [9,99,999,100], 
        [9,99,999,100], 
    	[900,901,902,100],
    ],
    [
        [1,99,999,100], 
        [1,99,999,100], 
    	[900,1000,902,100],
    ],
]) # (3, 3, 4)

In [76]:
arr_3.shape

(3, 3, 4)

In [69]:
print(arr_1.shape)
print(arr_2.shape)

(3,)
(2, 3)


In [65]:
print(arr_1.ndim)
print(arr_2.ndim)

1
2


In [ ]:
z = np.zeros((4,1))
o = np.ones((2,3))
r = np.arange(4,10,2)
l = np.linspace(0,10,5)
# np.random.uniform(0,1)
# np.random.normal(0,1)

In [279]:
f = np.full((2,3),7.)
f

array([[7., 7., 7.],
       [7., 7., 7.]])

In [280]:
f.dtype

dtype('float64')

In [282]:
f = np.full((2,3,2), 10)
f

array([[[10, 10],
        [10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10],
        [10, 10]]])

In [ ]:
arr_3 # 3,3,4 = 36

array([[[  10,   11,   12,  100],
        [  10,   11,   12,  100],
        [ 100,  111,  122,  100]],

       [[   9,   99,  999,  100],
        [   9,   99,  999,  100],
        [ 900,  901,  902,  100]],

       [[   1,   99,  999,  100],
        [   1,   99,  999,  100],
        [ 900, 1000,  902,  100]]])

In [307]:
arr_3 = np.full((3,3,4),7)
arr_3

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [310]:
arr_3.reshape((4,9,1))

array([[[7],
        [7],
        [7],
        [7],
        [7],
        [7],
        [7],
        [7],
        [7]],

       [[7],
        [7],
        [7],
        [7],
        [7],
        [7],
        [7],
        [7],
        [7]],

       [[7],
        [7],
        [7],
        [7],
        [7],
        [7],
        [7],
        [7],
        [7]],

       [[7],
        [7],
        [7],
        [7],
        [7],
        [7],
        [7],
        [7],
        [7]]])

In [313]:
arr_3.flatten().reshape((4,9))

array([[7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [316]:
arr_3.shape

(3, 3, 4)

In [315]:
for x in arr_3:
    print(x)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [333]:
arr_1 = np.linspace(10,20,5)
arr_2 = np.linspace(20,30,5)
arr_3 = np.linspace(30,40,5)

In [337]:
arr_f = np.array([
    arr_1,
    arr_2,
    arr_3,
])
arr_f

array([[10. , 12.5, 15. , 17.5, 20. ],
       [20. , 22.5, 25. , 27.5, 30. ],
       [30. , 32.5, 35. , 37.5, 40. ]])

In [ ]:
arr_f[1:, 2::2]

array([[25., 30.],
       [35., 40.]])

In [ ]:
arr_f[[0,2], 2:]

array([[15. , 17.5, 20. ],
       [35. , 37.5, 40. ]])