In [2]:
import numpy as np

In [10]:
l = [1,2,3,4]
arr = np.array(l)
np.arange(1,5)
np.linspace(1,4,4)

array([1., 2., 3., 4.])

In [13]:
arr = np.arange(-5,5)
arr

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [18]:
arr%2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [14]:
arr < 0

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [20]:
arr[(arr < 0) | (arr%2==0)]

array([-5, -4, -3, -2, -1,  0,  2,  4])

In [21]:
arr = np.array([10,12,25,33,44,50])
arr[arr%10==0]

array([10, 50])

In [22]:
import pandas as pd

In [ ]:
# %pip install pandas

In [31]:
yashlar = [10,12,25,33,44,50]

s1 = pd.Series(yashlar)
s2 = pd.Series([10,12,25,33,44,50])
s3 = pd.Series(
    [10,12,25,33,44,50],
    index=['ali', 'vali', 'hesen', 'gulnar', 'lale', 'fatma']
    )
s4 = pd.Series({
    'ali' : 10,
	'vali' : 12,
	'hesen' : 25,
	'gulnar' : 33,
	'lale' : 44,
	'fatma' : 50,
})
s4

ali       10
vali      12
hesen     25
gulnar    33
lale      44
fatma     50
dtype: int64

In [33]:
# s4['ali']
s4.loc['ali']
s4.iloc[0]

np.int64(10)

In [ ]:
s4.iloc[1:5]
s4.loc['vali':'lale']

ali       10
vali      12
hesen     25
gulnar    33
lale      44
dtype: int64

In [39]:
# s4.loc['ali'] = 40
s4.iloc[0] = 40
s4

ali       40
vali      12
hesen     25
gulnar    33
lale      44
fatma     50
dtype: int64

In [42]:
np.sin(s4)

ali       0.745113
vali     -0.536573
hesen    -0.132352
gulnar    0.999912
lale      0.017702
fatma    -0.262375
dtype: float64

In [43]:
s4

ali       40
vali      12
hesen     25
gulnar    33
lale      44
fatma     50
dtype: int64

In [62]:
s6 = pd.Series({
    'ali' : 30,
    'vali' : 12,
	'shemi' : 40,
})
s_total = s4 + s6
s_total

ali       70.0
fatma      NaN
gulnar     NaN
hesen      NaN
lale       NaN
shemi      NaN
vali      24.0
dtype: float64

In [59]:
ort = s_total.mean()
ort

np.float64(47.0)

In [64]:
# s_total.loc[s_total.isna()]
# s_total.loc[s_total.notna()]
s_total.loc[s_total.isna()] = ort
s_total

ali       70.0
fatma     47.0
gulnar    47.0
hesen     47.0
lale      47.0
shemi     47.0
vali      24.0
dtype: float64

In [72]:
s4.loc[s4%10 == 0]

ali      40
fatma    50
dtype: int64

In [67]:
s4

ali       40
vali      12
hesen     25
gulnar    33
lale      44
fatma     50
dtype: int64

In [73]:
s4.to_numpy()

array([40, 12, 25, 33, 44, 50])

In [74]:
s4.to_dict()

{'ali': 40, 'vali': 12, 'hesen': 25, 'gulnar': 33, 'lale': 44, 'fatma': 50}

In [75]:
s4

ali       40
vali      12
hesen     25
gulnar    33
lale      44
fatma     50
dtype: int64

In [78]:
s4.loc[s4<30] = np.nan
s4

ali       40.0
vali       NaN
hesen      NaN
gulnar    33.0
lale      44.0
fatma     50.0
dtype: float64

In [84]:
s4.argmin()

np.int64(3)

In [81]:
# s4[s4.isna()] = 100
s4.fillna(s4.max())

ali       40.0
vali      50.0
hesen     50.0
gulnar    33.0
lale      44.0
fatma     50.0
dtype: float64

In [ ]:
# s4.loc[s4 < 40] = 0
s4.mask(s4<40, 0)

ali       40.0
vali       NaN
hesen      NaN
gulnar     0.0
lale      44.0
fatma     50.0
dtype: float64

In [ ]:
b = [0,40,80]
s4.value_counts(dropna = False)

NaN     2
40.0    1
33.0    1
44.0    1
50.0    1
Name: count, dtype: int64

In [97]:
s4.value_counts?

Signature:
s4.value_counts(
    normalize: 'bool' = False,
    sort: 'bool' = True,
    ascending: 'bool' = False,
    bins=None,
    dropna: 'bool' = True,
) -> 'Series'
Docstring:
Return a Series containing counts of unique values.

The resulting object will be in descending order so that the
first element is the most frequently-occurring element.
Excludes NA values by default.

Parameters
----------
normalize : bool, default False
    If True then the object returned will contain the relative
    frequencies of the unique values.
sort : bool, default True
    Sort by frequencies when True. Preserve the order of the data when False.
ascending : bool, default False
    Sort in ascending order.
bins : int, optional
    Rather than count values, group them into half-open bins,
    a convenience for ``pd.cut``, only works with numeric data.
dropna : bool, default True
    Don't include counts of NaN.

Returns
-------
Series

See Also
--------
Series.count: Number of non-NA elements in a 

In [123]:
from pathlib import Path
csv_path = Path(r"C:\Users\user\Desktop\div\data\world_population.csv")
df = pd.read_csv(csv_path)
df.head(17)

Rank CCA3              Country           Capital      Continent  \
0     36  AFG          Afghanistan             Kabul           Asia   
1    138  ALB              Albania            Tirana         Europe   
2     34  DZA              Algeria           Algiers         Africa   
3    213  ASM       American Samoa         Pago Pago        Oceania   
4    203  AND              Andorra  Andorra la Vella         Europe   
5     42  AGO               Angola            Luanda         Africa   
6    224  AIA             Anguilla        The Valley  North America   
7    201  ATG  Antigua and Barbuda      Saint John’s  North America   
8     33  ARG            Argentina      Buenos Aires  South America   
9    140  ARM              Armenia           Yerevan           Asia   
10   198  ABW                Aruba        Oranjestad  North America   
11    55  AUS            Australia          Canberra        Oceania   
12    99  AUT              Austria            Vienna         Europe   
13    91  AZE           Azerbaijan              Baku           Asia   
14   176  BHS              Bahamas            Nassau  North America   
15   154  BHR              Bahrain            Manama           Asia   
16     8  BGD           Bangladesh             Dhaka           Asia   

    2022 Population  2020 Population  2015 Population  2010 Population  \
0        41128771.0       38972230.0       33753499.0       28189672.0   
1         2842321.0        2866849.0        2882481.0        2913399.0   
2        44903225.0       43451666.0       39543154.0       35856344.0   
3           44273.0          46189.0          51368.0          54849.0   
4           79824.0          77700.0          71746.0          71519.0   
5        35588987.0       33428485.0       28127721.0       23364185.0   
6           15857.0          15585.0          14525.0          13172.0   
7           93763.0          92664.0          89941.0          85695.0   
8        45510318.0       45036032.0       43257065.0       41100123.0   
9         2780469.0        2805608.0        2878595.0        2946293.0   
10         106445.0         106585.0         104257.0         100341.0   
11       26177413.0       25670051.0       23820236.0       22019168.0   
12        8939617.0        8907777.0        8642421.0        8362829.0   
13       10358074.0              NaN        9863480.0        9237202.0   
14         409984.0         406471.0         392697.0         373272.0   
15        1472233.0        1477469.0        1362142.0        1213645.0   
16      171186372.0      167420951.0      157830000.0      148391139.0   

    2000 Population  1990 Population  1980 Population  1970 Population  \
0        19542982.0       10694796.0       12486631.0       10752971.0   
1         3182021.0        3295066.0        2941651.0        2324731.0   
2        30774621.0       25518074.0       18739378.0       13795915.0   
3           58230.0          47818.0          32886.0          27075.0   
4           66097.0          53569.0          35611.0          19860.0   
5        16394062.0       11828638.0        8330047.0        6029700.0   
6           11047.0           8316.0           6560.0           6283.0   
7           75055.0          63328.0          64888.0          64516.0   
8        37070774.0       32637657.0       28024803.0       23842803.0   
9         3168523.0        3556539.0        3135123.0        2534377.0   
10          89101.0          65712.0          62267.0          59106.0   
11       19017963.0       17048003.0       14706322.0       12595034.0   
12        8010428.0        7678729.0        7547561.0        7465301.0   
13        8190337.0        7427836.0        6383060.0        5425317.0   
14         325014.0         270679.0         223752.0         179129.0   
15         711442.0         517418.0         362595.0         222555.0   
16      129193327.0      107147651.0       83929765.0       67541860.0   

    Area (km²)  Density (per km²)  Growth Rate  World Popul

In [120]:
s_pop = df['2022 Population']
s_pop

0      41128771.0
1       2842321.0
2      44903225.0
3         44273.0
4         79824.0
          ...    
229       11572.0
230      575986.0
231    33696614.0
232    20017675.0
233    16320537.0
Name: 2022 Population, Length: 234, dtype: float64

In [124]:
s_pop2 = s_pop[s_pop > 100_000_000]
s_pop2

16     1.711864e+08
27     2.153135e+08
41     1.425887e+09
57     1.109901e+08
63     1.233799e+08
92     1.417173e+09
93     2.755013e+08
102    1.239517e+08
131    1.275041e+08
149    2.185412e+08
156    2.358249e+08
163    1.155590e+08
171    1.447133e+08
221    3.382899e+08
Name: 2022 Population, dtype: float64

In [126]:
# s_pop2 + 50e6
s_pop2.apply(lambda pop : pop + 50e6)

16     2.211864e+08
27     2.653135e+08
41     1.475887e+09
57     1.609901e+08
63     1.733799e+08
92     1.467173e+09
93     3.255013e+08
102    1.739517e+08
131    1.775041e+08
149    2.685412e+08
156    2.858249e+08
163    1.655590e+08
171    1.947133e+08
221    3.882899e+08
Name: 2022 Population, dtype: float64

In [131]:
def f(pop):
	if pop > 100e6:
		return 'boyuk olke'
	else:
		return 'kicik olke'

s_pop_yeni = s_pop.apply(f)
df['2030_population_index'] = s_pop_yeni
df.head(3)

Rank CCA3      Country  Capital Continent  2022 Population  \
0    36  AFG  Afghanistan    Kabul      Asia       41128771.0   
1   138  ALB      Albania   Tirana    Europe        2842321.0   
2    34  DZA      Algeria  Algiers    Africa       44903225.0   

   2020 Population  2015 Population  2010 Population  2000 Population  \
0       38972230.0       33753499.0       28189672.0       19542982.0   
1        2866849.0        2882481.0        2913399.0        3182021.0   
2       43451666.0       39543154.0       35856344.0       30774621.0   

   1990 Population  1980 Population  1970 Population  Area (km²)  \
0       10694796.0       12486631.0       10752971.0    652230.0   
1        3295066.0        2941651.0        2324731.0     28748.0   
2       25518074.0       18739378.0       13795915.0   2381741.0   

   Density (per km²)  Growth Rate  World Population Percentage  \
0            63.0587       1.0257                         0.52   
1            98.8702       0.9957                         0.04   
2            18.8531       1.0164                         0.56   

  2030_population_index  
0            kicik olke  
1            kicik olke  
2            kicik olke

In [139]:
s_cont = df['Continent']

def inkisaf_sev_gore_ayir(qite):
    if qite == 'Europe' or qite == 'North America':
        return 'inkisaf etmis'
    else:
        return 'inkisaf eden'

s_cont_yeni = s_cont.apply(inkisaf_sev_gore_ayir)
df['ink_seviyesi'] = s_cont_yeni
df

Rank CCA3            Country           Capital Continent  \
0      36  AFG        Afghanistan             Kabul      Asia   
1     138  ALB            Albania            Tirana    Europe   
2      34  DZA            Algeria           Algiers    Africa   
3     213  ASM     American Samoa         Pago Pago   Oceania   
4     203  AND            Andorra  Andorra la Vella    Europe   
..    ...  ...                ...               ...       ...   
229   226  WLF  Wallis and Futuna          Mata-Utu   Oceania   
230   172  ESH     Western Sahara          El Aaiún    Africa   
231    46  YEM              Yemen             Sanaa      Asia   
232    63  ZMB             Zambia            Lusaka    Africa   
233    74  ZWE           Zimbabwe            Harare    Africa   

     2022 Population  2020 Population  2015 Population  2010 Population  \
0         41128771.0       38972230.0       33753499.0       28189672.0   
1          2842321.0        2866849.0        2882481.0        2913399.0   
2         44903225.0       43451666.0       39543154.0       35856344.0   
3            44273.0          46189.0          51368.0          54849.0   
4            79824.0          77700.0          71746.0          71519.0   
..               ...              ...              ...              ...   
229          11572.0          11655.0          12182.0          13142.0   
230         575986.0         556048.0         491824.0         413296.0   
231       33696614.0       32284046.0       28516545.0       24743946.0   
232       20017675.0       18927715.0              NaN       13792086.0   
233       16320537.0       15669666.0       14154937.0       12839771.0   

     2000 Population  1990 Population  1980 Population  1970 Population  \
0         19542982.0       10694796.0       12486631.0       10752971.0   
1          3182021.0        3295066.0        2941651.0        2324731.0   
2         30774621.0       25518074.0       18739378.0       13795915.0   
3            58230.0          47818.0          32886.0          27075.0   
4            66097.0          53569.0          35611.0          19860.0   
..               ...              ...              ...              ...   
229          14723.0          13454.0          11315.0           9377.0   
230         270375.0         178529.0         116775.0          76371.0   
231       18628700.0       13375121.0        9204938.0        6843607.0   
232        9891136.0        7686401.0        5720438.0        4281671.0   
233       11834676.0       10113893.0        7049926.0        5202918.0   

     Area (km²)  Density (per km²)  Growth Rate  World Population Percentage  \
0      652230.0            63.0587       1.0257                         0.52   
1       28748.0            98.8702       0.9957                         0.04   
2     2381741.0            18.8531       1.0164                         0.56   
3         199.0           222.4774       0.9831                         0.00   
4         468.0           170.5641       1.0100                         0.00   
..          ...                ...          ...                          ...   
229       142.0            81.4930       0.9953                         0.00   
230    266000.0             2.1654       1.0184                         0.01   
231    527968.0            63.8232       1.0217                         0.42   
232    752612.0            26.5976       1.0280                         0.25   
233    390757.0            41.7665       1.0204                         0.20   

    2030_population_index   ink_seviyesi  
0              kicik olke   inkisaf eden  
1              kicik olke  inkisaf etmis  
2              kicik olke   inkisaf eden  
3              kicik olke   inkisaf eden  
4              kicik olke  inkisaf etmis  
..                    ...            ...  
229            kicik olke   inkisaf eden  
230            kicik olke   inkisaf eden  
231            kicik olke   inkisaf eden  
232            kicik olke   ink

In [110]:
s_cont = df['Continent']
s_cont.value_counts()

Continent
Africa           57
Asia             50
Europe           50
North America    40
Oceania          23
South America    14
Name: count, dtype: int64

In [112]:
57 / s_cont.value_counts().sum()

np.float64(0.24358974358974358)

In [118]:
s_cont = df['Continent']
s_cont.value_counts(normalize=True) * 100

Continent
Africa           24.358974
Asia             21.367521
Europe           21.367521
North America    17.094017
Oceania           9.829060
South America     5.982906
Name: proportion, dtype: float64

In [141]:
s_c = df['Country']
s_c

0            Afghanistan
1                Albania
2                Algeria
3         American Samoa
4                Andorra
             ...        
229    Wallis and Futuna
230       Western Sahara
231                Yemen
232               Zambia
233             Zimbabwe
Name: Country, Length: 234, dtype: object

In [151]:
df.shape

(234, 19)

In [150]:
s_c.shape

(234,)

In [ ]:
np.array([
    [2,3,4],
    [4,5,5],
]).shape

In [153]:
s_country = df['Country']
s_country

0            Afghanistan
1                Albania
2                Algeria
3         American Samoa
4                Andorra
             ...        
229    Wallis and Futuna
230       Western Sahara
231                Yemen
232               Zambia
233             Zimbabwe
Name: Country, Length: 234, dtype: object

In [ ]:
'ab' + 'cd'

In [167]:
int('26')

26

In [168]:
int(False)

0

In [170]:
True + True

2

In [171]:
# s_country.isnull().value_counts()
s_country.isnull().sum()

np.int64(0)

In [179]:
s_cont.sort_values(ascending=False)

27     South America
227    South America
162    South America
64     South America
42     South America
           ...      
195           Africa
75            Africa
198           Africa
72            Africa
233           Africa
Name: Continent, Length: 234, dtype: object

In [183]:
s_cont.tail(3)

231      Asia
232    Africa
233    Africa
Name: Continent, dtype: object

In [188]:
s_cont

0         Asia
1       Europe
2       Africa
3      Oceania
4       Europe
        ...   
229    Oceania
230     Africa
231       Asia
232     Africa
233     Africa
Name: Continent, Length: 234, dtype: object

In [210]:
s_pop.nlargest(5)

41     1.425887e+09
92     1.417173e+09
221    3.382899e+08
93     2.755013e+08
156    2.358249e+08
Name: 2022 Population, dtype: float64

In [211]:
s_pop.max()

np.float64(1425887337.0)

In [191]:
s_cont.unique(), s_cont.nunique()

(array(['Asia', 'Europe', 'Africa', 'Oceania', 'North America',
        'South America'], dtype=object),
 6)

In [215]:
s_cont

0         Asia
1       Europe
2       Africa
3      Oceania
4       Europe
        ...   
229    Oceania
230     Africa
231       Asia
232     Africa
233     Africa
Name: Continent, Length: 234, dtype: object

In [217]:
s_country.is_unique

True

In [214]:
s_cont.is_unique

False

In [218]:
df

Rank CCA3            Country           Capital Continent  \
0      36  AFG        Afghanistan             Kabul      Asia   
1     138  ALB            Albania            Tirana    Europe   
2      34  DZA            Algeria           Algiers    Africa   
3     213  ASM     American Samoa         Pago Pago   Oceania   
4     203  AND            Andorra  Andorra la Vella    Europe   
..    ...  ...                ...               ...       ...   
229   226  WLF  Wallis and Futuna          Mata-Utu   Oceania   
230   172  ESH     Western Sahara          El Aaiún    Africa   
231    46  YEM              Yemen             Sanaa      Asia   
232    63  ZMB             Zambia            Lusaka    Africa   
233    74  ZWE           Zimbabwe            Harare    Africa   

     2022 Population  2020 Population  2015 Population  2010 Population  \
0         41128771.0       38972230.0       33753499.0       28189672.0   
1          2842321.0        2866849.0        2882481.0        2913399.0   
2         44903225.0       43451666.0       39543154.0       35856344.0   
3            44273.0          46189.0          51368.0          54849.0   
4            79824.0          77700.0          71746.0          71519.0   
..               ...              ...              ...              ...   
229          11572.0          11655.0          12182.0          13142.0   
230         575986.0         556048.0         491824.0         413296.0   
231       33696614.0       32284046.0       28516545.0       24743946.0   
232       20017675.0       18927715.0              NaN       13792086.0   
233       16320537.0       15669666.0       14154937.0       12839771.0   

     2000 Population  1990 Population  1980 Population  1970 Population  \
0         19542982.0       10694796.0       12486631.0       10752971.0   
1          3182021.0        3295066.0        2941651.0        2324731.0   
2         30774621.0       25518074.0       18739378.0       13795915.0   
3            58230.0          47818.0          32886.0          27075.0   
4            66097.0          53569.0          35611.0          19860.0   
..               ...              ...              ...              ...   
229          14723.0          13454.0          11315.0           9377.0   
230         270375.0         178529.0         116775.0          76371.0   
231       18628700.0       13375121.0        9204938.0        6843607.0   
232        9891136.0        7686401.0        5720438.0        4281671.0   
233       11834676.0       10113893.0        7049926.0        5202918.0   

     Area (km²)  Density (per km²)  Growth Rate  World Population Percentage  \
0      652230.0            63.0587       1.0257                         0.52   
1       28748.0            98.8702       0.9957                         0.04   
2     2381741.0            18.8531       1.0164                         0.56   
3         199.0           222.4774       0.9831                         0.00   
4         468.0           170.5641       1.0100                         0.00   
..          ...                ...          ...                          ...   
229       142.0            81.4930       0.9953                         0.00   
230    266000.0             2.1654       1.0184                         0.01   
231    527968.0            63.8232       1.0217                         0.42   
232    752612.0            26.5976       1.0280                         0.25   
233    390757.0            41.7665       1.0204                         0.20   

    2030_population_index   ink_seviyesi  
0              kicik olke   inkisaf eden  
1              kicik olke  inkisaf etmis  
2              kicik olke   inkisaf eden  
3              kicik olke   inkisaf eden  
4              kicik olke  inkisaf etmis  
..                    ...            ...  
229            kicik olke   inkisaf eden  
230            kicik olke   inkisaf eden  
231            kicik olke   inkisaf eden  
232            kicik olke   ink

In [ ]:
# CamelCase
# snake_case

In [234]:
s_yash = pd.Series([10,20,30], index=['ali', 'vali', 'gulnar'])
s_boy = pd.Series([150,160,170],index=['ali', 'hasan', 'gulnar'])

df1 = pd.DataFrame({
    'yash' : s_yash,
    'boy' : s_boy,
})

df2 = pd.DataFrame(
	np.array(
        [
            [ 10., 150.],
			[ 30., 170.],
			[ np.nan, 160.],
			[ 20.,  np.nan]
        ]
    ), 
    columns=['yash', 'boy'],
    index=['ali', 'vali', 'hesen', 'gulnar']
)
df2

yash    boy
ali     10.0  150.0
vali    30.0  170.0
hesen    NaN  160.0
gulnar  20.0    NaN

In [237]:
%pip install openpyxl xlsxwriter

  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)

   ---------------------------------------- 0/3 [xlsxwriter]
   ---------------------------------------- 0/3 [xlsxwriter]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   ---------------------------------------- 3/3 [openpyxl]

Note: you may need to restart the kernel to use updated packages.


In [238]:
# df1.to_csv('yash_boy.csv')
df1.to_excel('yash_boy.xlsx')


In [239]:
pd.read_excel('yash_boy.xlsx')

Unnamed: 0   yash         boy
0        ali   10.0       150.0
1     gulnar   30.0       170.0
2      hasan    NaN       160.0
3       vali   20.0         NaN
4      shemi  555.0  10000000.0

In [230]:
df1.to_numpy()

array([[ 10., 150.],
       [ 30., 170.],
       [ nan, 160.],
       [ 20.,  nan]])

In [ ]:
[0, ..., 9999]
[1, ..., 10000]