In [2]:
import numpy as np

In [ ]:
arr = np.array([
    [
        [
            [1,2,3],
            [4,5,6]
		], 
	]
])

arr.ndim # 
arr.shape # (1,1,2,3)
# arr[0][0][0][1]
# arr[0,0,0,1]
# arr[0][0][1][:]
# arr[0,0,1,:]
arr[0,0,1,...]

array([4, 5, 6])

In [ ]:
arr = np.array([
	[1,2,3],
	[4,5,6]
])

In [ ]:
arr = np.array([1,2,3])

arr.ndim
arr.shape # (3,)

1

In [ ]:
arr = np.array([
    [1],
    [2],
    [3]
])

arr.ndim # 2
arr.shape # (3,1)

2

In [20]:
arr1 = np.array([
	[1,2,3],
	[4,5,6]
]) # (2,3)

arr2 = np.array([1,2,3]) # (3,)

# (2,3,)
# np.array([
# [1,2,3],
# [1,2,3]
# ])

arr1 + arr2

array([[2, 4, 6],
       [5, 7, 9]])

In [21]:
arr1 = np.array([
	[1,2,3],
	[4,5,6]
]) # (2,3)

arr3 = np.array([
    [1],
    [2],
]) # (2,1)

# [
#     [1, 1, 1],
#     [2, 2, 2],
# ] (2, 3)
arr1 + arr3

array([[2, 3, 4],
       [6, 7, 8]])

In [32]:
v = np.array([2,3])
u = np.array([4,5])
v * u

array([ 8, 15])

In [33]:
v.dot(u)

np.int64(23)

In [41]:
m3 = np.array([
    [-1,-2],
    [-3,0],
])

In [ ]:
m1 = np.array([
    [1,2],
    [3,4],
])

m2 = np.array([
    [10,11,12],
    [13,14,15],
])

m1@m2 # (2,2) @ (2,3) = (2,3)

array([[36, 39, 42],
       [82, 89, 96]])

In [42]:
m1, m3

(array([[1, 2],
        [3, 4]]),
 array([[-1, -2],
        [-3,  0]]))

In [43]:
m1/m3

C:\Users\user\AppData\Local\Temp\ipykernel_26760\2025784844.py:1: RuntimeWarning: divide by zero encountered in divide
  m1/m3


array([[-1., -1.],
       [-1., inf]])

In [53]:
m1

array([[1, 2],
       [3, 4]])

In [55]:
np.e ** (0.69314718)

1.9999999988801092

In [52]:
np.log(m1)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [57]:
m1, m2, m3

(array([[1, 2],
        [3, 4]]),
 array([[10, 11, 12],
        [13, 14, 15]]),
 array([[-1, -2],
        [-3,  0]]))

In [58]:
m1, m3

(array([[1, 2],
        [3, 4]]),
 array([[-1, -2],
        [-3,  0]]))

In [60]:
np.hstack((m1, m3, m2))

array([[ 1,  2, -1, -2, 10, 11, 12],
       [ 3,  4, -3,  0, 13, 14, 15]])

In [63]:
m1,m2

(array([[1, 2],
        [3, 4]]),
 array([[10, 11, 12],
        [13, 14, 15]]))

In [65]:
np.vstack((m1, m2))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [ ]:
'ab' + 'ali' # concatenation
'ab' * 3 # replication

'ababab'

In [68]:
m1,m3

(array([[1, 2],
        [3, 4]]),
 array([[-1, -2],
        [-3,  0]]))

In [70]:
np.concatenate(
    (m1,m3),
	axis=1
)

array([[ 1,  2, -1, -2],
       [ 3,  4, -3,  0]])

In [77]:
m4 = np.array([
    [
        [1,2,3],
    	[4,5,6],
    ],
    [
        [11,12,13],
    	[14,15,16]
    ],
	
])

np.concatenate(
    (m4,m4),
    axis=2 
    )

array([[[ 1,  2,  3,  1,  2,  3],
        [ 4,  5,  6,  4,  5,  6]],

       [[11, 12, 13, 11, 12, 13],
        [14, 15, 16, 14, 15, 16]]])

In [78]:
arr = np.array([
    [ 0,  1,  2,  3],
	[ 4,  5,  6,  7],
	[ 8,  9, 10, 11],
	[12, 13, 14, 15],
	[16, 17, 18, 19],
	[20, 21, 22, 23]
])

arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [84]:
# np.vsplit(arr, 3)
np.hsplit(arr,3)

ValueError: array split does not result in an equal division

In [108]:
arr

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [86]:
arr.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [88]:
import math
math.sqrt([1,2,3,4])

TypeError: must be real number, not list

In [ ]:
arr = np.array([1,2,3,4])
np.sqrt(arr) == arr**(1/2)

array([ True,  True,  True,  True])

In [94]:
arr = np.arange(-5,6)
arr

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [97]:
mask = arr < 0
arr[mask]

array([-5, -4, -3, -2, -1])

In [106]:
mask

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False])

In [105]:
mask.sum()

np.int64(5)

In [ ]:
False + False

2

In [123]:
arr = np.array([
    [ 0,  1,  2,  3],
	[ 4,  0,  6,  7],
	[ 8,  9, 10, 11],
	[12, 13, 0, 15],
	[16, 17, 18, 19],
	[20, 21, 22, -1]
])

arr

array([[ 0,  1,  2,  3],
       [ 4,  0,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13,  0, 15],
       [16, 17, 18, 19],
       [20, 21, 22, -1]])

In [129]:
arr.argmin(axis=1)

array([0, 1, 0, 2, 0, 3])

In [122]:
np.min(
    np.array([ 0,  1,  2,  3]),
	np.array([ 4,  5,  6,  7])
)

TypeError: only integer scalar arrays can be converted to a scalar index

In [131]:
M = m1 @ m3
M

array([[ -7,  -2],
       [-15,  -6]])

In [133]:
M_inv = np.linalg.inv(M)
M_inv

array([[-0.5       ,  0.16666667],
       [ 1.25      , -0.58333333]])

In [134]:
M @ M_inv

array([[1.0000000e+00, 0.0000000e+00],
       [4.4408921e-16, 1.0000000e+00]])

In [ ]:
[
    [1,0],
    [0,1]
]

In [137]:
np.linalg.pinv(M) @ M

array([[ 1.00000000e+00,  1.11022302e-16],
       [-8.88178420e-16,  1.00000000e+00]])