In [21]:
import numpy as np
arr1 = np.full((2,4), 7.)
arr2 = np.full((2,4), 100.)
arr1

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [5]:
arr2

array([[100., 100., 100.],
       [100., 100., 100.]])

In [11]:
np.concatenate([arr1, arr2], axis=0)

array([[  7.,   7.,   7.],
       [  7.,   7.,   7.],
       [100., 100., 100.],
       [100., 100., 100.]])

In [12]:
np.concatenate([arr1, arr2], axis=1)

array([[  7.,   7.,   7., 100., 100., 100.],
       [  7.,   7.,   7., 100., 100., 100.]])

In [22]:
print(arr1)
arr1.sum()

[[7. 7. 7. 7.]
 [7. 7. 7. 7.]]


np.float64(56.0)

In [29]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
(
    np.array([ 1,  2,  3,  4]) + 
	np.array([ 5,  6,  7,  8]) + 
	np.array([ 9, 10, 11, 12])
) / 3

array([5., 6., 7., 8.])

In [32]:
np.arange(1,13).reshape(3,4).mean(axis=0)

array([5., 6., 7., 8.])

In [33]:
np.array([10, 26, 42]) / 4

array([ 2.5,  6.5, 10.5])

In [35]:
np.arange(1,13).reshape(3,4).mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [48]:
x = np.arange(1,13).reshape(3,2,2)
x

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [52]:
x.max(axis=2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [ ]:
[[ 1,  2],
[ 3,  4]], 

In [46]:
# np.max(x)
# x.max()
x.max(axis=0)

array([ 9, 10, 11, 12])

In [55]:
arr1

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [56]:
arr2.T

array([[100., 100.],
       [100., 100.],
       [100., 100.],
       [100., 100.]])

In [57]:
arr1 @ arr2.T

array([[2800., 2800.],
       [2800., 2800.]])

In [58]:
x = np.array([1,2,3,4]) 
y = np.array([100,102,103,104]) 

np.dot(x,y)

np.int64(1029)

In [61]:
# %pip install pandas

In [ ]:
import pandas as pd
from pathlib import Path
csv_path = Path(r"C:\Users\user\Desktop\div\data\world_population.csv")
csv_path

WindowsPath('C:/Users/user/Desktop/div/data/world_population.csv')

In [66]:
df = pd.read_csv(csv_path) # data-frame
df 

Rank CCA3            Country           Capital Continent  \
0      36  AFG        Afghanistan             Kabul      Asia   
1     138  ALB            Albania            Tirana    Europe   
2      34  DZA            Algeria           Algiers    Africa   
3     213  ASM     American Samoa         Pago Pago   Oceania   
4     203  AND            Andorra  Andorra la Vella    Europe   
..    ...  ...                ...               ...       ...   
229   226  WLF  Wallis and Futuna          Mata-Utu   Oceania   
230   172  ESH     Western Sahara          El Aaiún    Africa   
231    46  YEM              Yemen             Sanaa      Asia   
232    63  ZMB             Zambia            Lusaka    Africa   
233    74  ZWE           Zimbabwe            Harare    Africa   

     2022 Population  2020 Population  2015 Population  2010 Population  \
0         41128771.0       38972230.0       33753499.0       28189672.0   
1          2842321.0        2866849.0        2882481.0        2913399.0   
2         44903225.0       43451666.0       39543154.0       35856344.0   
3            44273.0          46189.0          51368.0          54849.0   
4            79824.0          77700.0          71746.0          71519.0   
..               ...              ...              ...              ...   
229          11572.0          11655.0          12182.0          13142.0   
230         575986.0         556048.0         491824.0         413296.0   
231       33696614.0       32284046.0       28516545.0       24743946.0   
232       20017675.0       18927715.0              NaN       13792086.0   
233       16320537.0       15669666.0       14154937.0       12839771.0   

     2000 Population  1990 Population  1980 Population  1970 Population  \
0         19542982.0       10694796.0       12486631.0       10752971.0   
1          3182021.0        3295066.0        2941651.0        2324731.0   
2         30774621.0       25518074.0       18739378.0       13795915.0   
3            58230.0          47818.0          32886.0          27075.0   
4            66097.0          53569.0          35611.0          19860.0   
..               ...              ...              ...              ...   
229          14723.0          13454.0          11315.0           9377.0   
230         270375.0         178529.0         116775.0          76371.0   
231       18628700.0       13375121.0        9204938.0        6843607.0   
232        9891136.0        7686401.0        5720438.0        4281671.0   
233       11834676.0       10113893.0        7049926.0        5202918.0   

     Area (km²)  Density (per km²)  Growth Rate  World Population Percentage  
0      652230.0            63.0587       1.0257                         0.52  
1       28748.0            98.8702       0.9957                         0.04  
2     2381741.0            18.8531       1.0164                         0.56  
3         199.0           222.4774       0.9831                         0.00  
4         468.0           170.5641       1.0100                         0.00  
..          ...                ...          ...                          ...  
229       142.0            81.4930       0.9953                         0.00  
230    266000.0             2.1654       1.0184                         0.01  
231    527968.0            63.8232       1.0217                         0.42  
232    752612.0            26.5976       1.0280                         0.25  
233    390757.0            41.7665       1.0204                         0.20  

[234 rows x 17 columns]

In [70]:
df[df['Country'] == 'Azerbaijan']

Rank CCA3     Country Capital Continent  2022 Population  2020 Population  \
13    91  AZE  Azerbaijan    Baku      Asia       10358074.0              NaN   

    2015 Population  2010 Population  2000 Population  1990 Population  \
13        9863480.0        9237202.0        8190337.0        7427836.0   

    1980 Population  1970 Population  Area (km²)  Density (per km²)  \
13        6383060.0        5425317.0     86600.0           119.6082   

    Growth Rate  World Population Percentage  
13       1.0044                         0.13

In [72]:
df['2022 Population'] # series

0      41128771.0
1       2842321.0
2      44903225.0
3         44273.0
4         79824.0
          ...    
229       11572.0
230      575986.0
231    33696614.0
232    20017675.0
233    16320537.0
Name: 2022 Population, Length: 234, dtype: float64

In [75]:
df['2022 Population'].to_dict()

{0: 41128771.0,
 1: 2842321.0,
 2: 44903225.0,
 3: 44273.0,
 4: 79824.0,
 5: 35588987.0,
 6: 15857.0,
 7: 93763.0,
 8: 45510318.0,
 9: 2780469.0,
 10: 106445.0,
 11: 26177413.0,
 12: 8939617.0,
 13: 10358074.0,
 14: 409984.0,
 15: 1472233.0,
 16: 171186372.0,
 17: 281635.0,
 18: 9534954.0,
 19: 11655930.0,
 20: 405272.0,
 21: 13352864.0,
 22: 64184.0,
 23: 782455.0,
 24: 12224110.0,
 25: 3233526.0,
 26: 2630296.0,
 27: 215313498.0,
 28: 31305.0,
 29: 449002.0,
 30: 6781953.0,
 31: 22673762.0,
 32: 12889576.0,
 33: 16767842.0,
 34: 27914536.0,
 35: 38454327.0,
 36: 593149.0,
 37: 68706.0,
 38: 5579144.0,
 39: 17723315.0,
 40: 19603733.0,
 41: 1425887337.0,
 42: 51874024.0,
 43: 836774.0,
 44: 17011.0,
 45: 5180829.0,
 46: 4030358.0,
 47: 11212191.0,
 48: 191163.0,
 49: 1251488.0,
 50: 10493986.0,
 51: 5882261.0,
 52: 1120849.0,
 53: 72737.0,
 54: 11228821.0,
 55: 99010212.0,
 56: 18001000.0,
 57: 110990103.0,
 58: 6336392.0,
 59: 1674908.0,
 60: 3684032.0,
 61: 1326062.0,
 62: nan,
 63:

In [76]:
df['2022 Population'].to_numpy()

array([4.11287710e+07, 2.84232100e+06, 4.49032250e+07, 4.42730000e+04,
       7.98240000e+04, 3.55889870e+07, 1.58570000e+04, 9.37630000e+04,
       4.55103180e+07, 2.78046900e+06, 1.06445000e+05, 2.61774130e+07,
       8.93961700e+06, 1.03580740e+07, 4.09984000e+05, 1.47223300e+06,
       1.71186372e+08, 2.81635000e+05, 9.53495400e+06, 1.16559300e+07,
       4.05272000e+05, 1.33528640e+07, 6.41840000e+04, 7.82455000e+05,
       1.22241100e+07, 3.23352600e+06, 2.63029600e+06, 2.15313498e+08,
       3.13050000e+04, 4.49002000e+05, 6.78195300e+06, 2.26737620e+07,
       1.28895760e+07, 1.67678420e+07, 2.79145360e+07, 3.84543270e+07,
       5.93149000e+05, 6.87060000e+04, 5.57914400e+06, 1.77233150e+07,
       1.96037330e+07, 1.42588734e+09, 5.18740240e+07, 8.36774000e+05,
       1.70110000e+04, 5.18082900e+06, 4.03035800e+06, 1.12121910e+07,
       1.91163000e+05, 1.25148800e+06, 1.04939860e+07, 5.88226100e+06,
       1.12084900e+06, 7.27370000e+04, 1.12288210e+07, 9.90102120e+07,
      

In [73]:
d = {'a':'salam', 'b':'sagol'}
d


{'a': 'salam', 'b': 'sagol'}

In [74]:
d['a']

'salam'

In [77]:
df

Rank CCA3            Country           Capital Continent  \
0      36  AFG        Afghanistan             Kabul      Asia   
1     138  ALB            Albania            Tirana    Europe   
2      34  DZA            Algeria           Algiers    Africa   
3     213  ASM     American Samoa         Pago Pago   Oceania   
4     203  AND            Andorra  Andorra la Vella    Europe   
..    ...  ...                ...               ...       ...   
229   226  WLF  Wallis and Futuna          Mata-Utu   Oceania   
230   172  ESH     Western Sahara          El Aaiún    Africa   
231    46  YEM              Yemen             Sanaa      Asia   
232    63  ZMB             Zambia            Lusaka    Africa   
233    74  ZWE           Zimbabwe            Harare    Africa   

     2022 Population  2020 Population  2015 Population  2010 Population  \
0         41128771.0       38972230.0       33753499.0       28189672.0   
1          2842321.0        2866849.0        2882481.0        2913399.0   
2         44903225.0       43451666.0       39543154.0       35856344.0   
3            44273.0          46189.0          51368.0          54849.0   
4            79824.0          77700.0          71746.0          71519.0   
..               ...              ...              ...              ...   
229          11572.0          11655.0          12182.0          13142.0   
230         575986.0         556048.0         491824.0         413296.0   
231       33696614.0       32284046.0       28516545.0       24743946.0   
232       20017675.0       18927715.0              NaN       13792086.0   
233       16320537.0       15669666.0       14154937.0       12839771.0   

     2000 Population  1990 Population  1980 Population  1970 Population  \
0         19542982.0       10694796.0       12486631.0       10752971.0   
1          3182021.0        3295066.0        2941651.0        2324731.0   
2         30774621.0       25518074.0       18739378.0       13795915.0   
3            58230.0          47818.0          32886.0          27075.0   
4            66097.0          53569.0          35611.0          19860.0   
..               ...              ...              ...              ...   
229          14723.0          13454.0          11315.0           9377.0   
230         270375.0         178529.0         116775.0          76371.0   
231       18628700.0       13375121.0        9204938.0        6843607.0   
232        9891136.0        7686401.0        5720438.0        4281671.0   
233       11834676.0       10113893.0        7049926.0        5202918.0   

     Area (km²)  Density (per km²)  Growth Rate  World Population Percentage  
0      652230.0            63.0587       1.0257                         0.52  
1       28748.0            98.8702       0.9957                         0.04  
2     2381741.0            18.8531       1.0164                         0.56  
3         199.0           222.4774       0.9831                         0.00  
4         468.0           170.5641       1.0100                         0.00  
..          ...                ...          ...                          ...  
229       142.0            81.4930       0.9953                         0.00  
230    266000.0             2.1654       1.0184                         0.01  
231    527968.0            63.8232       1.0217                         0.42  
232    752612.0            26.5976       1.0280                         0.25  
233    390757.0            41.7665       1.0204                         0.20  

[234 rows x 17 columns]

In [86]:
# df['Country']
x = df.loc[1]
# df.iloc[1]

x

Rank                                 138
CCA3                                 ALB
Country                          Albania
Capital                           Tirana
Continent                         Europe
2022 Population                2842321.0
2020 Population                2866849.0
2015 Population                2882481.0
2010 Population                2913399.0
2000 Population                3182021.0
1990 Population                3295066.0
1980 Population                2941651.0
1970 Population                2324731.0
Area (km²)                       28748.0
Density (per km²)                98.8702
Growth Rate                       0.9957
World Population Percentage         0.04
Name: 1, dtype: object

In [88]:
x.loc['1990 Population']

np.float64(3295066.0)

In [89]:
x.iloc[10]

np.float64(3295066.0)

In [139]:
a = [25,40,30,35,60]
b = ['ali', 'vali', 'hesen', 'huseyn', 'lale']
d = dict(zip(b,a))
# {k:v for k,v in list(zip(a,b))}
d

{'ali': 25, 'vali': 40, 'hesen': 30, 'huseyn': 35, 'lale': 60}

In [142]:
{v:k for k,v in d.items()}

{25: 'ali', 40: 'vali', 30: 'hesen', 35: 'huseyn', 60: 'lale'}

In [133]:
s1 = pd.Series(
    [25,40,30,35,60]
    )
s2 = pd.Series(
    [25,40,np.nan,35,60],
	index=['ali', 'vali', 'hesen', 'huseyn', 'lale']
)
s3 = pd.Series(
    {'ali': 25, 
     'vali': 40, 
     'hesen': 30, 
     'huseyn': 35, 
     'lale': 60}
)
s3[s3 < 50]

ali       25
vali      40
hesen     30
huseyn    35
dtype: int64

In [ ]:
# s3['ali']
s3.loc['hesen']
s3.iloc[2]

np.int64(30)

In [147]:
pd.Series({v:k for k,v in s3.to_dict().items()})

25       ali
40      vali
30     hesen
35    huseyn
60      lale
dtype: object

In [148]:
l = [1,2,2,3,4]
l[2] = 100
l

[1, 2, 100, 3, 4]

In [150]:
s3

ali       25
vali      40
hesen     30
huseyn    35
lale      60
dtype: int64

In [153]:
s3.iloc[0] = 300
s3

ali       300
vali       40
hesen      30
huseyn     35
lale       60
dtype: int64

In [164]:
kohne_index = s3.index.to_list()
kohne_index[0] = 'gulnar'
yeni_index = kohne_index.copy()

s3.index = yeni_index
s3

gulnar    300
vali       40
hesen      30
huseyn     35
lale       60
dtype: int64

In [166]:
s3.loc['gulnar'] = 30
s3

gulnar    30
vali      40
hesen     30
huseyn    35
lale      60
dtype: int64

In [167]:
s3

gulnar    30
vali      40
hesen     30
huseyn    35
lale      60
dtype: int64

In [169]:
s3.iloc[1:4]

vali      40
hesen     30
huseyn    35
dtype: int64

In [171]:
s3.loc['vali':'huseyn']

vali      40
hesen     30
huseyn    35
dtype: int64

In [ ]:
s4 = pd.Series(
    {'ali': 25, 
     'vali': 40, 
     'hesen': 30, 
     'ali': 35, 
     'lale': 60}
)
s4

ali      35
vali     40
hesen    30
lale     60
dtype: int64

In [173]:
s3

gulnar    30
vali      40
hesen     30
huseyn    35
lale      60
dtype: int64

In [174]:
s3 = pd.Series(
    {'ali': 25, 
     'vali': 40, 
     'hesen': 30, 
     'huseyn': 35, 
     'lale': 60}
)

s4 = pd.Series(
    {'ali': 25, 
     'elovset': 40, 
     'shucaet': 30, 
     'qezenfer': 35, 
     'lale': 60}
)

s3 + s4

ali          50.0
elovset       NaN
hesen         NaN
huseyn        NaN
lale        120.0
qezenfer      NaN
shucaet       NaN
vali          NaN
dtype: float64

In [178]:
s3.name = 'yashlar1'
s4.name = 'yashlar2'
s3

ali       25
vali      40
hesen     30
huseyn    35
lale      60
Name: yashlar1, dtype: int64

In [181]:
pd.concat(
    [s3.to_frame(), s4.to_frame()], axis=1
    )

yashlar1  yashlar2
ali           25.0      25.0
vali          40.0       NaN
hesen         30.0       NaN
huseyn        35.0       NaN
lale          60.0      60.0
elovset        NaN      40.0
shucaet        NaN      30.0
qezenfer       NaN      35.0

In [ ]:
s3[s3 < 50] = 90
s3

ali       90
vali      90
hesen     90
huseyn    90
lale      60
Name: yashlar1, dtype: int64

In [191]:
s3 = pd.Series(
    {'ali': 25, 
     'vali': 40, 
     'hesen': 30, 
     'huseyn': 35, 
     'lale': 60}
)

s3 = s3.mask(s3==30, 100)
s3

ali        25
vali       40
hesen     100
huseyn     35
lale       60
dtype: int64