In [ ]:
# %pip install numpy

1

In [4]:
import numpy as np
np.sqrt(9)

np.float64(3.0)

In [17]:
l = [10,20,30,40,50]
arr1 = np.array(l)

arr2 = np.array([10,20,30,40,50])

arr3 = np.arange(10,60,10)
arr4 = np.linspace(10,50,5)
arr4

array([10., 20., 30., 40., 50.])

In [32]:
l = [
    [1,2,3], 
    [4,5,6]
    ]
arr5 = np.array(l)
print(arr5.size) # 6
print(arr5.ndim) # 2
print(arr5.shape) # (2,3)

6
2
(2, 3)


In [24]:
arr5.ndim

2

In [ ]:
arr7 = np.array([1,2,3,4])
print(arr7.size) # 4
print(arr7.ndim) # 1
print(arr7.shape) # (4,)

1

In [31]:
arr8 = np.array([
    [
        [1,2,3],
    	[4,5,6],
    ],
    [
        [10,20,30],
    	[40,50,60],
    ],
])
print(arr8.size)
print(arr8.ndim)
print(arr8.shape)

12
3
(2, 2, 3)


In [ ]:
(2,2,3)

In [34]:
arr9 = np.array([
    [
        [
			[1,2,3],
			[4,5,6],
		],
		[
			[10,20,30],
			[40,50,60],
		]
    ],
    [
        [
			[1,2,3],
			[4,5,6],
		],
		[
			[10,20,30],
			[40,50,60],
		]
    ],
])
print(arr9.size) # 24
print(arr9.ndim) # 4
print(arr9.shape) # (2,2,2,3)

24
4
(2, 2, 2, 3)


In [ ]:
arr10 = np.array([[[1,2,3,4]]]) # np.array([1,2,3,4])
print(arr10.size) # 4
print(arr10.ndim) # 3
print(arr10.shape) # (1,1,4)

In [43]:
z = np.zeros((3,4))
n = np.ones((3,4))
f = np.full((2,3), '17.')
f

array([['17.', '17.', '17.'],
       ['17.', '17.', '17.']], dtype='<U3')

In [48]:
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
np.unique(z, return_counts=True)

(array([0.]), array([12]))

In [54]:
a = np.array([1,2,3])
b = np.array([11,12,13,14])
a+b

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [94]:
def f(x,y):
    return x+10*y 
#(1,2) -> 1 + 10*2 = 21

arr = np.fromfunction(f, (4,5))
arr

array([[ 0., 10., 20., 30., 40.],
       [ 1., 11., 21., 31., 41.],
       [ 2., 12., 22., 32., 42.],
       [ 3., 13., 23., 33., 43.]])

In [80]:
arr[1:3, 1::2] # (4,5)

array([[11., 31.],
       [12., 32.]])

In [98]:
# arr[0:2]
id_setir = [0,2]
id_sutun = [2,4]
arr[np.ix_(id_setir, id_sutun)]

array([[20., 40.],
       [22., 42.]])

In [89]:
arr = np.array([100,200,300,400])
arr[0]

np.int64(100)

In [91]:
x = np.float64(100)
x.ndim # 0
x.shape # ()
x

np.float64(100.0)

In [112]:
l = [1,2,3,4,5]
l[3:] = 100,101,102
l

[1, 2, 3, 100, 101, 102]

In [113]:
arr = np.array([1,2,3,4,5])
arr[3:] = 100,101,102
arr

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [115]:
arr = np.array([1,2,3,4,5])
arr[2:] = 100,101,102
arr

array([  1,   2, 100, 101, 102])

In [116]:
arr

array([  1,   2, 100, 101, 102])

In [118]:
arr >= 100

array([False, False,  True,  True,  True])

In [120]:
arr[arr >= 100]

array([100, 101, 102])

In [123]:
arr = np.array([2,3,4,5,6,7])
arr[arr%2 == 0]

array([2, 4, 6])

In [139]:
arr

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [140]:
arr = np.arange(-5,6)
# mask1 = arr < 0
# mask2 = arr%2 == 0
# arr[mask1 & mask2]
arr[(arr < 0) & (arr%2 == 0)]
arr[(arr < 0) | (arr%2 == 0)]

array([-5, -4, -3, -2, -1,  0,  2,  4])

In [137]:
mask1, mask2

(array([ True,  True,  True,  True,  True, False, False, False, False,
        False, False]),
 array([False,  True, False,  True, False,  True, False,  True, False,
         True, False]))

In [135]:
arr = np.array([10,15,20,30,35])
arr[arr%10 == 0]

array([10, 20, 30])

In [119]:
# [True if reqem >= 100 else False for reqem in arr]

In [148]:
array1 = np.array([1, 2, 3])
array2 = np.array([0, 5, 6])
array1 / array2 + 5

C:\Users\user\AppData\Local\Temp\ipykernel_6216\4172382063.py:3: RuntimeWarning: divide by zero encountered in divide
  array1 / array2 + 5


array([inf, 5.4, 5.5])

In [151]:
np.nan / 2

nan

In [ ]:
arr1 = np.array([
    [1, 2, 3], 
    [4, 5, 6]
]) # ndim==2 , shape==(2,3)

arr2 = np.array([10, 20, 30]) # ndim==1, shape==(3,)

# (2,3)
# (2,3)
# ([
# [10, 20, 30],
# [10, 20, 30],
# ]) 

arr1 + arr2

array([[11, 22, 33],
       [14, 25, 36]])

In [ ]:
arr1 = np.array([
    [1, 2, 3], 
    [4, 5, 6]
]) # ndim==2 , shape==(2,3)

arr2 = np.array([
    [10, 20, 30],
    ]) # ndim==2, shape==(1,3)

#(2,3)
#(1,3)
arr1 + arr2

array([[11, 22, 33],
       [14, 25, 36]])