In [ ]:
class Mashin:
	mühərrik = True
	ishe_salinib = False

	def __init__(self, m_markasi):
		self.marka = m_markasi

	# def ishe_sal(self):
	# 	self.ishe_salinib = True
	# 	return 'xodlandi'
	# @classmethod
	# def ishe_sal(cls):
	# 	cls.ishe_salinib = True
	# 	return 'xodlandi'
	@staticmethod
	def kimise_vur():
		return 'filankesi vurdum'
    
m = Mashin('toyota')
# print(m.ishe_sal())
# m.ishe_salinib # True
Mashin.ishe_sal()

True

In [10]:
maas = list(range(100,500,100))
bonus = list(range(10,50,10))

maas, bonus

([100, 200, 300, 400], [10, 20, 30, 40])

In [12]:
dovrlerin_sayi = len(maas)
dovrlerin_sayi

4

In [14]:
bosh_list = []
for i in range(dovrlerin_sayi):
	ea = maas[i] + bonus[i]
	bosh_list.append(ea)

bosh_list

[110, 220, 330, 440]

In [15]:
maas + bonus

[100, 200, 300, 400, 10, 20, 30, 40]

In [ ]:
# %pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [21]:
import numpy as np
np.array(maas) + np.array(bonus)

array([110, 220, 330, 440])

In [22]:
np.array(maas)*2

array([200, 400, 600, 800])

In [ ]:
arr1 = np.array([1,2,3,4])

l = [1,2,3,4]
arr2 = np.array(l)

arr3 = np.array((1,2,3,4))

arr4 = np.array([1,2,3,4.2])
arr6 = np.array(['ab', 'adfasb', 'adf'])

arr6

array(['ab', 'adəfasb', 'adf'], dtype='<U7')

In [40]:
arr4

array([1. , 2. , 3. , 4.2])

In [39]:
arr4.ndim

1

In [46]:
arr4.shape # (a,)

(4,)

In [47]:
arr5 = np.array([
    [1,2,3],
    [4,5,6],
])
arr5

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
arr5.ndim

2

In [49]:
arr5.shape # (2,3)

(2, 3)

In [50]:
arr6 = np.array([
    [
        [1,2,3],
    	[4,5,6],
    ],
    [
        [1,2,3],
    	[4,5,6],
    ]
])
arr6

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [51]:
arr6.ndim

3

In [ ]:
arr6.shape # (2,2,3)

In [54]:
arr7 = np.array([[[[1,2,3]]]])
arr7.ndim

4

In [55]:
arr7.shape # (1,1,1,3)

(1, 1, 1, 3)

In [ ]:
# import numpy as np

In [61]:
x = np.ones((2,3))
y = x * 5
y

array([[5., 5., 5.],
       [5., 5., 5.]])

In [63]:
y+np.ones((2,3))

array([[6., 6., 6.],
       [6., 6., 6.]])

In [65]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
np.full((2,4), 17.)

array([[17., 17., 17., 17.],
       [17., 17., 17., 17.]])

In [69]:
np.array(range(10,30,3))

array([10, 13, 16, 19, 22, 25, 28])

In [68]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [71]:
np.linspace(0,100,19)

array([  0.        ,   5.55555556,  11.11111111,  16.66666667,
        22.22222222,  27.77777778,  33.33333333,  38.88888889,
        44.44444444,  50.        ,  55.55555556,  61.11111111,
        66.66666667,  72.22222222,  77.77777778,  83.33333333,
        88.88888889,  94.44444444, 100.        ])

In [78]:
np.sqrt([
    [1,2,3],
    [4,5,6],
]).shape

(2, 3)

In [87]:
np.linspace(0,10,5).sum().shape # ()

()

In [88]:
arr6

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
arr6 

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [100]:
for i,nese in enumerate(arr6):
    print(i,nese)
    for icindeki_nese in nese:
        print(icindeki_nese)

0 [[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]
1 [[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]


In [97]:
arr6.dtype

dtype('int64')

In [ ]:
# ndim = 3
# shape = (2,2,3)
# size = 12

In [102]:
arr6

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [106]:
arr6.shape

(2, 2, 3)

In [107]:
arr6.reshape((3,5))

ValueError: cannot reshape array of size 12 into shape (3,5)