In [2]:
import numpy as np

In [10]:
x = np.array([1,2,3,4])
y = np.array([
	[1,2],
	[3,4]
	])

x.size

4

In [36]:
arr = np.random.randint(0,10,(3,4,2))
arr

array([[[9, 2],
        [8, 2],
        [6, 0],
        [4, 5]],

       [[0, 5],
        [8, 7],
        [3, 2],
        [2, 1]],

       [[6, 8],
        [2, 3],
        [6, 2],
        [0, 7]]], dtype=int32)

In [40]:
arr.mean(axis=2)

array([[5.5, 5. , 3. , 4.5],
       [2.5, 7.5, 2.5, 1.5],
       [7. , 2.5, 4. , 3.5]])

In [33]:
np.array([5, 6, 6, 3]) + \
np.array([6, 0, 3, 1]) +  \
np.array([7, 0, 9, 9])

array([18,  6, 18, 13])

In [51]:
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,4))

arr1, arr2

(array([[8, 6, 7],
        [6, 3, 2],
        [2, 5, 0]], dtype=int32),
 array([[6, 0, 3, 7],
        [7, 4, 0, 0],
        [4, 6, 4, 1]], dtype=int32))

In [ ]:
[[8, 6, 7],
[6, 3, 2],
[2, 5, 0]]
[[6, 0, 3, 7],
[7, 4, 0, 0],
[4, 6, 4, 1]]

In [62]:
np.concat([arr1, arr2], axis=1)

array([[8, 6, 7, 6, 0, 3, 7],
       [6, 3, 2, 7, 4, 0, 0],
       [2, 5, 0, 4, 6, 4, 1]], dtype=int32)

In [73]:
arr = np.array([1,2,3])[np.newaxis, :]
# arr
np.repeat(arr, 3, axis=0).flatten()

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [76]:
np.array([1,2,3]) % 2

array([1, 0, 1])

In [77]:
np.array([1,2,3]) + np.array([10,20,30])

array([11, 22, 33])

In [86]:
arr1 = np.random.randint(0,10,size=(4,))
arr2  = np.random.randint(0,10,size=(3,4))

np.repeat(arr1[np.newaxis, :],3,0)

array([[0, 0, 5, 1],
       [0, 0, 5, 1],
       [0, 0, 5, 1]], dtype=int32)

In [82]:
arr2

array([[7, 6, 9, 2],
       [5, 3, 5, 1],
       [8, 1, 2, 2]], dtype=int32)

In [91]:
arr1

array([0, 0, 5, 1], dtype=int32)

In [92]:
arr2

array([[0, 7, 9, 5],
       [3, 7, 2, 3],
       [1, 2, 7, 7]], dtype=int32)

In [90]:
np.repeat(arr1[np.newaxis, :],3,0) + arr2

array([[ 0,  7, 14,  6],
       [ 3,  7,  7,  4],
       [ 1,  2, 12,  8]], dtype=int32)

In [89]:
arr1 + arr2

array([[ 0,  7, 14,  6],
       [ 3,  7,  7,  4],
       [ 1,  2, 12,  8]], dtype=int32)

In [87]:
arr2

array([[0, 7, 9, 5],
       [3, 7, 2, 3],
       [1, 2, 7, 7]], dtype=int32)

In [ ]:
arr1 = np.random.randint(0,10,size=(4,3,2))
arr2  = np.random.randint(0,10,size=(2))

arr1, arr2

#(4,3,2)
#(4,3,2)

(array([[[8, 9],
         [7, 3],
         [8, 8]],
 
        [[6, 3],
         [2, 9],
         [4, 7]],
 
        [[6, 2],
         [9, 8],
         [5, 7]],
 
        [[2, 1],
         [5, 6],
         [9, 3]]], dtype=int32),
 array([5, 7], dtype=int32))

In [103]:
np.repeat(np.repeat(arr2.reshape((1,1,2)), 3, axis=1), 4, axis=0)
#(1,1,2)

array([[[5, 2],
        [5, 2],
        [5, 2]],

       [[5, 2],
        [5, 2],
        [5, 2]],

       [[5, 2],
        [5, 2],
        [5, 2]],

       [[5, 2],
        [5, 2],
        [5, 2]]], dtype=int32)

In [105]:
arr1 + arr2

array([[[13, 16],
        [12, 10],
        [13, 15]],

       [[11, 10],
        [ 7, 16],
        [ 9, 14]],

       [[11,  9],
        [14, 15],
        [10, 14]],

       [[ 7,  8],
        [10, 13],
        [14, 10]]], dtype=int32)

In [ ]:
arr1 = np.random.randint(0,10,size=(5,1))
arr2  = np.random.randint(0,10,size=(5,4))

arr1, arr2

#(5,1)
#(5,4)

(array([[0],
        [0],
        [9],
        [9],
        [6]], dtype=int32),
 array([[4, 4, 8, 9],
        [4, 4, 3, 4],
        [6, 5, 2, 8],
        [5, 9, 8, 5],
        [2, 9, 3, 8]], dtype=int32))

In [109]:
np.repeat(arr1, 4, axis=1)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [6, 6, 6, 6]], dtype=int32)

In [113]:
arr1 = np.random.randint(0,10,size=(5,1))
arr2  = np.random.randint(0,10,size=(4))

arr1+arr2

#(5,1)
#(1,4)

array([[10,  8,  9, 13],
       [14, 12, 13, 17],
       [14, 12, 13, 17],
       [15, 13, 14, 18],
       [15, 13, 14, 18]], dtype=int32)

In [112]:
arr2[np.newaxis, :]

array([[4, 0, 7, 7]], dtype=int32)

In [117]:
x = arr1+arr2
x[1:3, -2:]

array([[13, 17],
       [13, 17]], dtype=int32)

In [127]:
x[np.ix_([1,2],[2,3]) ]

array([[13, 17],
       [13, 17]], dtype=int32)

In [126]:
np.ix_?

Signature:       np.ix_(*args)
Call signature:  np.ix_(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function ix_ at 0x0000024D368DB6A0>
File:            c:\users\user\miniconda3\envs\ds\lib\site-packages\numpy\lib\_index_tricks_impl.py
Docstring:      
Construct an open mesh from multiple sequences.

This function takes N 1-D sequences and returns N outputs with N
dimensions each, such that the shape is 1 in all but one dimension
and the dimension with the non-unit shape value cycles through all
N dimensions.

Using `ix_` one can quickly construct index arrays that will index
the cross product. ``a[np.ix_([1,3],[2,5])]`` returns the array
``[[a[1,2] a[1,5]], [a[3,2] a[3,5]]]``.

Parameters
----------
args : 1-D sequences
    Each sequence should be of integer or boolean type.
    Boolean sequences will be interpreted as boolean masks for the
    corresponding dimension (equivalent to passing in
    ``np.nonzero(boolean_sequence)``).

Returns
-------
out 

In [165]:
arr = np.random.normal(50, 30, size=(6,4))
arr
# arr[np.ix_([1,3], [1,3])]

array([[-20.0259182 ,  27.95234688,  87.05028824,  46.80871644],
       [ 25.40876343,  43.63398392,  12.66880973,  18.77468804],
       [ 27.80091712,  94.7443309 ,  33.79850805,   9.61558675],
       [ 83.66241428,  63.71810318,  23.30943407,  46.91054234],
       [-22.45464256,  52.41993759,  51.99160021,   7.29861158],
       [ 76.51469761,  36.83848312,  61.47409952,  60.45383329]])

In [166]:
arr[np.ix_([1,3], [1,3])]

array([[43.63398392, 18.77468804],
       [63.71810318, 46.91054234]])

In [ ]:
arr 

array([[-20.0259182 ,  27.95234688,  87.05028824,  46.80871644],
       [ 25.40876343,  43.63398392,  12.66880973,  18.77468804],
       [ 27.80091712,  94.7443309 ,  33.79850805,   9.61558675],
       [ 83.66241428,  63.71810318,  23.30943407,  46.91054234],
       [-22.45464256,  52.41993759,  51.99160021,   7.29861158],
       [ 76.51469761,  36.83848312,  61.47409952,  60.45383329]])

In [173]:
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,4))

arr1, arr2

(array([[1, 8, 6],
        [5, 0, 6],
        [0, 8, 4]], dtype=int32),
 array([[7, 1, 9, 1],
        [6, 9, 0, 9],
        [1, 3, 7, 5]], dtype=int32))

In [176]:
arr1 @ np.linalg.inv(arr1)

array([[ 1.00000000e+00,  1.11022302e-16,  4.44089210e-16],
       [-4.44089210e-16,  1.00000000e+00,  4.44089210e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [ ]:
np.linalg.re

In [179]:
np.concat([arr1, np.identity(3)], axis=1)

array([[1., 8., 6., 1., 0., 0.],
       [5., 0., 6., 0., 1., 0.],
       [0., 8., 4., 0., 0., 1.]])

In [174]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [169]:
arr1 @ arr2

array([[ 57,  32,  82,  70],
       [ 77, 110, 110,  97],
       [ 45,  52,  68,  59]], dtype=int32)

In [171]:
arr1.shape, arr2.shape

((3, 3), (3, 4))