In [2]:
import numpy as np

In [13]:
x = np.array([1, 2, 3])[:, np.newaxis]
y  = np.array([10, 20, 30])[:, np.newaxis]

x, y

(array([[1],
        [2],
        [3]]),
 array([[10],
        [20],
        [30]]))

In [14]:
np.concat([x,y], axis=1)

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [25]:
!pip install pandas -q

In [11]:
import pandas as pd

In [18]:
x = pd.Series([1, 2, 3])
y = pd.Series([10, 20, 30])

df = pd.DataFrame({'x adli sutun': x, 'y adli sutun': y})
df

,x adli sutun,y adli sutun
0,1,10
1,2,20
2,3,30


In [52]:
s2 = pd.Series(
	[10, 20, 30], 
	index=['y1', 'y2', 'y3'],
	dtype='float')

s3 = pd.Series(
	[100, 200, 300], 
	index=['y1', 'y2', 'y3'],
	dtype='float')
s2 + s3

y1    110.0
y2    220.0
y3    330.0
dtype: float64

In [90]:
adlar = ['ali', 'vali', 'hesen', 'lale', 'huseyn']
adlar = np.random.choice(adlar, 50, p=[0.5, 0.1, 0.1, 0.1, 0.2])
adlar = pd.Series(adlar, name='ad')
adlar

0       vali
1        ali
2        ali
3        ali
4        ali
5        ali
6        ali
7        ali
8        ali
9        ali
10      vali
11     hesen
12    huseyn
13      lale
14     hesen
15       ali
16    huseyn
17       ali
18    huseyn
19       ali
20    huseyn
21       ali
22       ali
23       ali
24     hesen
25    huseyn
26       ali
27     hesen
28       ali
29       ali
30       ali
31      vali
32       ali
33     hesen
34       ali
35    huseyn
36       ali
37       ali
38     hesen
39    huseyn
40      vali
41    huseyn
42    huseyn
43       ali
44       ali
45    huseyn
46       ali
47       ali
48       ali
49       ali
Name: ad, dtype: str

In [91]:
yash = np.random.randint(0,100,50)
yashlar = pd.Series(yash, name='yash')
yashlar

0     87
1     46
2     93
3     33
4     91
5     42
6     82
7     65
8     70
9     84
10    79
11    28
12    57
13    80
14    13
15    58
16    17
17    58
18    85
19    65
20    51
21    12
22    18
23    93
24    24
25    57
26     2
27     8
28    33
29    72
30    96
31    67
32    11
33    72
34    30
35    54
36    63
37    56
38    96
39    36
40    35
41    70
42    46
43    37
44    83
45    60
46     4
47    61
48    35
49     2
Name: yash, dtype: int32

In [100]:
df = pd.concat([adlar, yashlar], axis=1)
mask =df['yash'] % 10 == 0
df[mask]

,ad,yash
8,ali,70
13,lale,80
34,ali,30
41,huseyn,70
45,huseyn,60


In [41]:
adlar = ['ali', 'vali', 'hesen', 'lale', 'huseyn']
indeksler = [f"y{i+1}" for i in range(len(adlar))]

s1 = pd.Series(
	adlar,
	index=indeksler, 
	name='qesey sutun'
	)
s1

y1       ali
y2      vali
y3     hesen
y4      lale
y5    huseyn
Name: qesey sutun, dtype: str

In [143]:
adlar = df['ad']
yashlar = df['yash']

In [148]:
boylar = np.random.normal(180, 10, 50)
boylar = pd.Series(boylar, name='boy')

In [174]:
# pd.concat([adlar, yashlar, boylar], axis=1)
df = pd.DataFrame({
	adlar.name : adlar, 
	yashlar.name : yashlar, 
	boylar.name : boylar, 
})

mask_ad = df['ad'] == 'ali'
mask_yash = (df['yash'] >= 30) & (df['yash'] <= 60)
mask_boy = (df['boy'] >= 180.0) | (df['boy'] <= 170.0)
mask = (~mask_ad) & mask_boy & mask_yash
df[mask]

,ad,yash,boy
12,huseyn,57,189.430261
25,huseyn,57,182.019597
39,huseyn,36,181.595859
40,vali,35,185.631306


In [190]:
mask = df['yash'] <= 30
# df.loc[mask, 'ad'] = 'zulfiyye'
# df
df.loc[mask, 'ad'] = 'xanim'
df

,ad,yash,boy
0,vali,87,187.786945
1,ali,46,169.287794
2,ali,93,198.185098
3,ali,33,181.150718
4,ali,91,183.946023
5,ali,42,172.951449
6,ali,82,172.720290
7,ali,65,185.822179
8,ali,70,183.892182
9,ali,84,207.096623


In [192]:
df.loc[2:10, ['ad', 'boy']]

,ad,boy
2,ali,198.185098
3,ali,181.150718
4,ali,183.946023
5,ali,172.951449
6,ali,172.720290
7,ali,185.822179
8,ali,183.892182
9,ali,207.096623
10,vali,160.176835


In [203]:
df.loc[['i5','i7','i10'], ['boy', 'ad']]

,boy,ad
i5,183.946023,ali
i7,172.720290,ali
i10,207.096623,ali


In [204]:
df.iloc[[5,7,10], [0,2]]

,ad,boy
i6,ali,172.951449
i8,ali,185.822179
i11,vali,160.176835


In [208]:
df['ad']['i5':'i7']

i5    ali
i6    ali
i7    ali
Name: ad, dtype: str

In [217]:
ad2 = adlar.unique().to_numpy()
yash2 = np.array([10,20,np.nan,40,50])

df2 = pd.DataFrame({
	'ad' : ad2,
	'yash' : yash2
})

df2

,ad,yash
0,vali,10.0
1,ali,20.0
2,zulfiyye,NaN
3,huseyn,40.0
4,hesen,50.0


In [232]:
df2.loc[1, 'ad'] = np.nan
df2

,ad,yash
0,vali,10.0
1,NaN,20.0
2,zulfiyye,NaN
3,huseyn,40.0
4,hesen,50.0


In [235]:
df2[df2['ad'] != 'vali']

,ad,yash
1,NaN,20.0
2,zulfiyye,NaN
3,huseyn,40.0
4,hesen,50.0


In [199]:
indeksler = [f"i{i+1}" for i in range(len(df))]
df.index = indeksler
df

,ad,yash,boy
i1,vali,87,187.786945
i2,ali,46,169.287794
i3,ali,93,198.185098
i4,ali,33,181.150718
i5,ali,91,183.946023
i6,ali,42,172.951449
i7,ali,82,172.720290
i8,ali,65,185.822179
i9,ali,70,183.892182
i10,ali,84,207.096623


50

In [195]:
df

,ad,yash,boy
0,vali,87,187.786945
1,ali,46,169.287794
2,ali,93,198.185098
3,ali,33,181.150718
4,ali,91,183.946023
5,ali,42,172.951449
6,ali,82,172.720290
7,ali,65,185.822179
8,ali,70,183.892182
9,ali,84,207.096623


In [142]:
adlar = df[['ad']]
df.loc[0:4, 'yash']

0    87
1    46
2    93
3    33
4    91
Name: yash, dtype: int32

In [21]:
df['x adli sutun'].values

array([1, 2, 3])

In [ ]:
x = [10,20]

x = 5

In [ ]:
yashlar

0     87
1     46
2     93
3     33
4     91
5     42
6     82
7     65
8     70
9     84
10    79
11    28
12    57
13    80
14    13
15    58
16    17
17    58
18    85
19    65
20    51
21    12
22    18
23    93
24    24
25    57
26     2
27     8
28    33
29    72
30    96
31    67
32    11
33    72
34    30
35    54
36    63
37    56
38    96
39    36
40    35
41    70
42    46
43    37
44    83
45    60
46     4
47    61
48    35
49     2
Name: yash, dtype: int32

In [105]:
s2.index

Index(['y1', 'y2', 'y3'], dtype='str')

In [236]:
from pathlib import Path
excel_path = r"C:\Users\user\Desktop\Book2.xlsx"
excel_path = Path(excel_path)
excel_path

WindowsPath('C:/Users/user/Desktop/Book2.xlsx')

In [238]:
!pip install openpyxl xlsxwriter

  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
  Using cached xlsxwriter-3.2.9-py3-none-any.whl.metadata (2.7 kB)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached xlsxwriter-3.2.9-py3-none-any.whl (175 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)

   ---------------------------------------- 0/3 [xlsxwriter]
   ---------------------------------------- 0/3 [xlsxwriter]
   ---------------------------------------- 0/3 [xlsxwriter]
   ---------------------------------------- 0/3 [xlsxwriter]
   ------------- -------------------------- 1/3 [et-xmlfile]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   ------------------------

In [241]:
df = pd.read_excel(excel_path)
df

,seherler,ehalisi
0,baki,3.3
1,sumqayit,NaN
2,gence,0.1


In [243]:
df.loc[1, 'ehalisi'] = 0.4
df

,seherler,ehalisi
0,baki,3.3
1,sumqayit,0.4
2,gence,0.1


In [249]:
df.to_excel(excel_path)