In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,54,5,6,6,6])

In [61]:
arr = np.random.randint(0,10,size=(2,4,3,5))
arr.shape

(2, 4, 3, 5)

In [62]:
arr

array([[[[9, 0, 6, 9, 6],
         [1, 5, 9, 5, 6],
         [2, 7, 1, 2, 4]],

        [[7, 4, 9, 3, 8],
         [4, 4, 9, 9, 5],
         [3, 6, 4, 1, 3]],

        [[6, 8, 0, 4, 5],
         [0, 0, 1, 0, 1],
         [9, 0, 6, 8, 8]],

        [[3, 2, 4, 2, 8],
         [3, 4, 9, 6, 4],
         [4, 1, 9, 8, 9]]],


       [[[4, 3, 3, 1, 3],
         [5, 6, 7, 7, 2],
         [1, 9, 0, 4, 1]],

        [[5, 9, 5, 6, 9],
         [6, 6, 9, 0, 1],
         [3, 4, 8, 2, 6]],

        [[9, 0, 6, 1, 8],
         [3, 0, 3, 3, 8],
         [7, 7, 3, 8, 5]],

        [[8, 6, 0, 5, 0],
         [9, 3, 4, 9, 4],
         [5, 9, 8, 4, 0]]]], dtype=int32)

In [ ]:
arr[0, ...]

array([[0, 5, 7],
       [4, 4, 6],
       [8, 0, 0],
       [2, 4, 1]], dtype=int32)

In [35]:
arr

array([[[  0,   8,   8,   2,   0],
        [  9,   7,   9,   9,   9],
        [  5,   7,   0,   7,   6]],

       [[100,   1, 100,   1, 100],
        [  3,   6,   4,   0,   7],
        [  3,   3,   8,   7,   8]],

       [[100,   4, 100,   5, 100],
        [  3,   0,   4,   5,   9],
        [  5,   3,   6,   9,   5]],

       [[  2,   6,   5,   9,   6],
        [  5,   3,   8,   5,   8],
        [  2,   3,   6,   7,   5]]], dtype=int32)

In [47]:
l = [1,2,3,4,5]
l[1:2] = [10,20,30,40,50]
l

[1, 10, 20, 30, 40, 50, 3, 4, 5]

In [53]:
a = np.array([1,2,3,4,5])
a[1:3] = np.array([100,500])
a

array([  1, 100, 500,   4,   5])

In [69]:
arr = np.random.randint(0,100,size=(4,3,5))
arr

array([[[13, 35, 42, 57, 64],
        [14, 79, 85, 73, 45],
        [94, 90, 30, 82, 27]],

       [[36, 45, 68, 48, 52],
        [42, 52, 80, 40, 17],
        [12, 95, 51, 38, 56]],

       [[73,  7, 15, 41, 76],
        [85, 41, 66, 17,  0],
        [ 4, 48, 89, 12, 54]],

       [[94, 41, 93, 49, 97],
        [68, 91, 78, 37, 86],
        [21, 21, 80, 65,  2]]], dtype=int32)

In [73]:
mask = arr % 3 == 0
mask

array([[[False, False,  True,  True, False],
        [False, False, False, False,  True],
        [False,  True,  True, False,  True]],

       [[ True,  True, False,  True, False],
        [ True, False, False, False, False],
        [ True, False,  True, False, False]],

       [[False, False,  True, False, False],
        [False, False,  True, False,  True],
        [False,  True, False,  True,  True]],

       [[False, False,  True, False, False],
        [False, False,  True, False, False],
        [ True,  True, False, False, False]]])

In [111]:
boy.shape, yash.shape

((20, 1), (20, 1))

In [128]:
yash = np.random.normal(25, 5, size=(20,1)).astype('int')
boy = np.random.normal(180, 10, size=(20,1)).astype('int')
yeni = np.concat([yash, boy], axis=1)
yeni

array([[ 18, 164],
       [ 28, 172],
       [ 18, 182],
       [ 22, 180],
       [ 32, 183],
       [ 19, 178],
       [ 26, 160],
       [ 24, 197],
       [ 23, 188],
       [ 20, 164],
       [ 26, 167],
       [ 19, 160],
       [ 22, 178],
       [ 21, 195],
       [ 33, 194],
       [ 20, 192],
       [ 27, 186],
       [ 28, 182],
       [ 31, 179],
       [ 15, 191]])

In [133]:
adlar[mask]

array([['fatime'],
       ['ali'],
       ['ali'],
       ['ali'],
       ['ali'],
       ['lale'],
       ['hesen'],
       ['hesen'],
       ['ali'],
       ['veli']], dtype='<U6')

In [131]:
mask = yeni[:, 1] > 180
yeni[mask]

array([[ 18, 182],
       [ 32, 183],
       [ 24, 197],
       [ 23, 188],
       [ 21, 195],
       [ 33, 194],
       [ 20, 192],
       [ 27, 186],
       [ 28, 182],
       [ 15, 191]])

In [137]:
np.vstack([yash, boy])

array([[ 18],
       [ 28],
       [ 18],
       [ 22],
       [ 32],
       [ 19],
       [ 26],
       [ 24],
       [ 23],
       [ 20],
       [ 26],
       [ 19],
       [ 22],
       [ 21],
       [ 33],
       [ 20],
       [ 27],
       [ 28],
       [ 31],
       [ 15],
       [164],
       [172],
       [182],
       [180],
       [183],
       [178],
       [160],
       [197],
       [188],
       [164],
       [167],
       [160],
       [178],
       [195],
       [194],
       [192],
       [186],
       [182],
       [179],
       [191]])

In [143]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([100,200,300,400,500])
arr1 + arr2

array([101, 202, 303, 404, 505])

In [151]:
arr3 = np.random.randint(0,10, (4,5))
arr3

array([[3, 7, 3, 0, 2],
       [3, 1, 4, 7, 1],
       [2, 7, 4, 6, 0],
       [8, 1, 3, 8, 3]], dtype=int32)

In [167]:
arr3.reshape((2,1, 10))

array([[[3, 7, 3, 0, 2, 3, 1, 4, 7, 1]],

       [[2, 7, 4, 6, 0, 8, 1, 3, 8, 3]]], dtype=int32)

In [166]:
arr3.reshape((2,10))[:,np.newaxis]

array([[[3, 7, 3, 0, 2, 3, 1, 4, 7, 1]],

       [[2, 7, 4, 6, 0, 8, 1, 3, 8, 3]]], dtype=int32)

In [174]:
arr3.reshape((1,4,5))

array([[[3, 7, 3, 0, 2],
        [3, 1, 4, 7, 1],
        [2, 7, 4, 6, 0],
        [8, 1, 3, 8, 3]]], dtype=int32)

In [175]:
arr3

array([[3, 7, 3, 0, 2],
       [3, 1, 4, 7, 1],
       [2, 7, 4, 6, 0],
       [8, 1, 3, 8, 3]], dtype=int32)

In [176]:
arr3.reshape(4,5,1)

array([[[3],
        [7],
        [3],
        [0],
        [2]],

       [[3],
        [1],
        [4],
        [7],
        [1]],

       [[2],
        [7],
        [4],
        [6],
        [0]],

       [[8],
        [1],
        [3],
        [8],
        [3]]], dtype=int32)

In [181]:
arr3[..., np.newaxis]

array([[[3],
        [7],
        [3],
        [0],
        [2]],

       [[3],
        [1],
        [4],
        [7],
        [1]],

       [[2],
        [7],
        [4],
        [6],
        [0]],

       [[8],
        [1],
        [3],
        [8],
        [3]]], dtype=int32)

In [184]:
arr3

array([[3, 7, 3, 0, 2],
       [3, 1, 4, 7, 1],
       [2, 7, 4, 6, 0],
       [8, 1, 3, 8, 3]], dtype=int32)

In [190]:
np.expand_dims(arr3, axis=2)

array([[[3],
        [7],
        [3],
        [0],
        [2]],

       [[3],
        [1],
        [4],
        [7],
        [1]],

       [[2],
        [7],
        [4],
        [6],
        [0]],

       [[8],
        [1],
        [3],
        [8],
        [3]]], dtype=int32)