In [9]:
import pandas as pd
import numpy as np

In [3]:
from sklearn.datasets import load_iris
iris = load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [11]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [19]:
X = iris['data']
y = iris['target']
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False)

X = iris['data']
y = iris['target']
y = ohe.fit_transform(y[:, np.newaxis])

X_train, X_test, y_train, y_test = train_test_split(
    X, 
    y, 
    test_size=0.2)

X_test.shape, y_test.shape

((30, 4), (30, 3))

In [27]:
X_train[0, :]

array([5.4, 3.9, 1.7, 0.4])

In [28]:
y_train[0, :]

array([1., 0., 0.])

In [62]:
x = np.array([
    [1. , 5.4, 3.9, 1.3, 0.4],
    [1. , 5.8, 2.7, 3.9, 1.2]
    ])
th = np.array([
	[ 0.30471708, -1.03998411,  0.7504512 ],
	[ 0.94056472, -1.95103519, -1.30217951],
	[ 0.1278404 , -0.31624259, -0.01680116],
	[-0.85304393,  0.87939797,  0.77779194],
	[ 0.0660307 ,  1.12724121,  0.46750934]
])
z = x @ th

def softmax(z):
    return (np.exp(z) / np.sum(np.exp(z), axis=1, keepdims=True))

h = softmax(z)
np.argmax(h, axis=1)

array([0, 0])

In [58]:
np.exp(z)

array([[1.21486033e+02, 1.34732221e-05, 5.80689415e-03],
       [1.74183988e+01, 2.18767361e-04, 3.86521331e-02]])

In [51]:
np.sum(np.exp(z), axis=1, keepdims=True)

array([[121.49185307],
       [ 17.45726969]])

In [ ]:
(np.exp(z) / np.sum(np.exp(z), axis=1, keepdims=True)).round(4)

array([[1.    , 0.    , 0.    ],
       [0.9978, 0.    , 0.0022]])

In [43]:
z

array([[  4.7997993 , -11.21480639,  -5.14870942],
       [  2.85752705,  -8.42750167,  -3.25315332]])

array([121.49185307,  17.45726969])

In [38]:
s = np.exp(4.7997993) + np.exp(-11.21480639) + np.exp(-5.14870942)
(np.exp(-5.14870942) / s).round(4)

np.float64(0.0)


$$\nabla J(\mathbf{\theta}) = \frac{1}{m} \mathbf{X}^T (\mathbf{H} - \mathbf{Y})$$

In [108]:
from sklearn.preprocessing import add_dummy_feature
eta = 0.1
n_epoch = 60000
X_train_b = add_dummy_feature(X_train)
m, n = X_train_b.shape
m, K = y_train.shape

def softmax(Z):
    return np.exp(Z) / np.sum(np.exp(Z), axis=1, keepdims=True)

rng = np.random.default_rng(seed=123)
Theta = rng.standard_normal(size=(n, K))

for epoch in range(n_epoch):
	Z = X_train_b @ Theta
	H = softmax(Z)
	gradient = 1/m * X_train_b.T @ (H - y_train)
	Theta = Theta - eta * gradient
Theta

array([[ 0.35124402,  8.65686893, -9.07709568],
       [ 3.2570604 ,  0.874217  , -2.43996829],
       [ 4.98555011, -0.02261925, -5.37403774],
       [-7.80966171, -0.1918808 ,  6.2503903 ],
       [-2.69468237, -4.38200361,  8.59803183]])

In [109]:
X_test_b = add_dummy_feature(X_test)
Z = X_test_b @ Theta
H = softmax(Z)
y_pred = np.argmax(H, axis=1)
y_pred

array([0, 0, 0, 1, 0, 2, 2, 2, 1, 2, 1, 0, 2, 2, 0, 1, 0, 1, 1, 2, 0, 2,
       0, 1, 2, 2, 1, 1, 0, 2])

In [110]:
y_act = np.argmax(y_test, axis=1)
y_act

array([0, 0, 0, 1, 0, 2, 2, 2, 1, 2, 1, 0, 2, 2, 0, 1, 0, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 1, 1, 0, 2])

In [111]:
acc = (y_pred == y_act).sum() / len(y_pred)
acc

np.float64(0.9666666666666667)

In [112]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(X_train, np.argmax(y_train, axis=1))
y_pred = clf.predict(X_test)
y_pred

array([0, 0, 0, 1, 0, 2, 2, 2, 1, 2, 1, 0, 2, 2, 0, 1, 0, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 1, 1, 0, 2])

In [113]:
y_pred == y_act

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [114]:
acc = (y_pred == y_act).sum() / len(y_pred)
acc

np.float64(1.0)