In [5]:
import torch
import numpy as np
# import pandas as pd

In [4]:
torch.__version__

'2.11.0+cpu'

In [10]:
arr1 = np.array([
	[1,4,7],
	[2,3,6]
])
arr1

array([[1, 4, 7],
       [2, 3, 6]])

In [12]:
arr2 = np.array([
	[1.0,4,7],
	[2,3,6]
])
arr2

array([[1., 4., 7.],
       [2., 3., 6.]])

In [17]:
arr1.ndim

2

In [27]:
t1 = torch.tensor([
	[1,4,7],
	[2,3,6]
])

t2 = torch.tensor([
	[1.0,4,7],
	[2,3,6]
], dtype=torch.float64)
t1+t2

tensor([[ 2.,  8., 14.],
        [ 4.,  6., 12.]], dtype=torch.float64)

In [30]:
t1 = torch.FloatTensor([
	[1,4,7],
	[2,3,6]
])
t2 = torch.FloatTensor([
	[1.0,4,7],
	[2,3,6]
])
t1+t2

tensor([[ 2.,  8., 14.],
        [ 4.,  6., 12.]])

In [34]:
torch.from_numpy(arr1)

tensor([[1, 4, 7],
        [2, 3, 6]])

In [36]:
arr1[0,1]

np.int64(4)

In [39]:
t1

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [40]:
arr1

array([[1, 4, 7],
       [2, 3, 6]])

In [42]:
def sigmoid(z):
	return 1 / (1+np.exp(-z))
sigmoid(arr1)

array([[0.73105858, 0.98201379, 0.99908895],
       [0.88079708, 0.95257413, 0.99752738]])

In [60]:
t1.sigmoid()

tensor([[0.7311, 0.9820, 0.9991],
        [0.8808, 0.9526, 0.9975]])

In [50]:
if torch.cuda.is_available():
	device = "cuda"
else: 
	device = "cpu"

device

'cpu'

In [51]:
t1.to(device)

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [56]:
x = torch.tensor(5.0, requires_grad=True)
x

tensor(5., requires_grad=True)

In [57]:
f = x ** 2
f

tensor(25., grad_fn=<PowBackward0>)

In [58]:
f.backward()

In [59]:
x.grad

tensor(10.)

In [64]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()
X = housing['data']
y = housing['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8)
X_valid, X_test, y_valid, y_test = train_test_split(X_test, y_test, train_size=0.5)

In [67]:
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
X_valid = torch.FloatTensor(X_valid)

In [72]:
X_train

tensor([[   3.7277,   38.0000,    5.6258,  ...,    2.8425,   37.9400,
         -122.3200],
        [   6.4018,   42.0000,    5.4809,  ...,    2.4733,   34.1200,
         -118.5800],
        [   6.2356,   42.0000,    4.6361,  ...,    1.9388,   33.8800,
         -118.4000],
        ...,
        [   1.6875,   19.0000,    5.2792,  ...,    2.8970,   33.9200,
         -116.7700],
        [   4.2685,   32.0000,    5.5579,  ...,    2.8079,   34.1000,
         -117.8800],
        [   2.9000,   12.0000,    3.6628,  ...,    3.0802,   34.1700,
         -118.2900]])

In [75]:
means = X_train.mean(axis=0, keepdim=True)
std = X_train.std(axis=0, keepdim=True)

In [77]:
X_train = (X_train - means) / std
X_test = (X_test - means) / std
X_valid = (X_valid - means) / std